version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=scaffold'
      - 'POSTGRES_PASSWORD=scaffoldpass'
      - 'POSTGRES_USER=scaffolduser'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - scaffold_network

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - scaffold_network
    command: redis-server --appendonly yes


volumes:
  postgres_data:
  redis_data:

networks:
  scaffold_network:
    driver: bridge